#!/usr/bin/env texlua

---@diagnostic disable: lowercase-global
module = "cvd"

sourcefiledir = "src"
sourcefiles = { "*.dtx", "*.ins", "*.lua" }
unpackfiles = { "*.ins" }
installfiles = { "*.sty", "*.lua" }
-- The .lua file needs to be treated as both source and installable
-- Since it's not generated by docstrip, add it to unpacksuppfiles
unpacksuppfiles = { "*.lua" }

docfiledir = "docs"
typesetfiles = { "*.tex" }
docfiles = { "cvd.pdf" }
textfiles = { "*.md", "LICENSE" }
checkengines = { "luatex" }
checksuppfiles = { "*.tex" }

packtdszip = false

uploadconfig = {
	pkg = "cvd",
	version = "0.2.0",
	author = "Johan Larsson, Simon Pfahler",
	uploader = "Johan Larsson",
	email = "johan@jolars.co",
	update = false,
	license = "mit",
	summary = "Color vision deficiency simulation for LaTeX documents",
	description = "Simulate color vision deficiencies in LaTeX documents, including "
		.. "protanopia, deuteranopia, and tritanopia. This package provides "
		.. "a few simple commands that allow you to control both the type "
		.. "of color deficiency and the severity of the simulation.",
	ctanPath = "/macros/latex/contrib/cvd",
	repository = "https://github.com/jolars/cvd",
	bugtracker = "https://github.com/jolars/cvd/issues",
	topic = "colour,typesetting",
	announcement_file = "ctan_announcement.txt",
}
